"""empty message

Revision ID: 8c20d9c7aadd
Revises: ec92db30b96a
Create Date: 2024-03-13 13:00:04.209871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c20d9c7aadd'
down_revision = 'ec92db30b96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('monthly_freq', sa.Float(), nullable=False))
        batch_op.drop_column('start_year')
        batch_op.drop_column('end_year')
        batch_op.drop_column('end_month')
        batch_op.drop_column('start_month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_month', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('end_month', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('end_year', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('start_year', sa.INTEGER(), nullable=False))
        batch_op.drop_column('monthly_freq')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
