"""empty message

Revision ID: a2a3a5d263c7
Revises: 6e97f5d2604d
Create Date: 2024-03-13 11:50:58.476986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a3a5d263c7'
down_revision = '6e97f5d2604d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ad_type', sa.String(length=6), nullable=False),
    sa.Column('start_month', sa.INTEGER(), nullable=False),
    sa.Column('start_year', sa.INTEGER(), nullable=False),
    sa.Column('end_month', sa.INTEGER(), nullable=False),
    sa.Column('end_year', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ads_client_id'))

    op.drop_table('ads')
    # ### end Alembic commands ###
