"""empty message

Revision ID: ea279dd38408
Revises: 8c20d9c7aadd
Create Date: 2024-03-13 13:22:05.220261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea279dd38408'
down_revision = '8c20d9c7aadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_text', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_column('ad_text')

    # ### end Alembic commands ###
