"""empty message

Revision ID: ef5759fc2812
Revises: b5ff905b0527
Create Date: 2024-03-13 13:40:19.459587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5759fc2812'
down_revision = 'b5ff905b0527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ads')
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('text', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))
        batch_op.drop_column('ad_text')
        batch_op.drop_column('ad_type')
        batch_op.drop_column('ad_note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_note', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('ad_type', sa.VARCHAR(length=6), nullable=False))
        batch_op.add_column(sa.Column('ad_text', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('note')
        batch_op.drop_column('text')
        batch_op.drop_column('type')

    op.create_table('_alembic_tmp_ads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('community', sa.VARCHAR(length=24), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('monthly_freq', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
